/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef demo2_CONSTANTS_H
#define demo2_CONSTANTS_H

#include "demo2_types.h"

namespace myfirst {

class demo2Constants {
 public:
  demo2Constants();

};

extern const demo2Constants g_demo2_constants;

} // namespace

#endif
