/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "demo2_constants.h"

namespace myfirst {

const demo2Constants g_demo2_constants;

demo2Constants::demo2Constants() {
}

} // namespace

